### ISSUE TITLE
add "what to expect" / "how to prepare" to website

### ISSUE THREAD

**Issue by brenna** [nodeschool/toronto#16]
- bring your own laptop
- install Node beforehand
- workshops are self-directed, selected from the [NodeSchool workshoppers list](http://nodeschool.io/#workshopper-list) 
- can work on own projects if you prefer
- there will be mentors available to help with both workshoppers and personal projects

**Comment by andrewdamelio** [comment]
added in PR https://github.com/nodeschool/toronto/pull/19
