### ISSUE TITLE
When will the next event be announced for the 19th?

### ISSUE THREAD

**Issue by mhdatie** [nodeschool/toronto#18]

**Comment by brenna** [comment]
Hi @MohamadAtieh,
We're still trying to firm up a venue, so it's looking like we may end up hosting the next event on the 26th instead. We'll send out details as soon as it's confirmed. Apologies for the incomplete info on the site.

**Comment by mhdatie** [comment]
@brenna Awesome! Thanks :+1:

**Comment by brenna** [comment]
@MohamadAtieh Sept 26th is a go! https://ti.to/nodeschool-toronto/september-2015

**Comment by mhdatie** [comment]
@brenna Registered, thanks for letting me know!
