### ISSUE TITLE
October Check list

### ISSUE THREAD

**Issue by Rchristiani** [nodeschool/toronto#20]
- [x] Email notification, as soon as event is confirmed.
- [x] Tweet as soon as event is confirmed.
- [ ] Email Reminder, few days before.
- [ ] Twitter Reminder, few days before.
- [x] Mentor roll call.
- [ ] Coffee order for event.
- [ ] Update main Node School Site
- [x] Update Node School Toronto Site
- [x] buy more nodeSchool stickers?
- [ ] Get 2-3 people to do small talks.

**Comment by andrewdamelio** [comment]
@Rchristiani we are so good on sticker front :)

**Comment by Rchristiani** [comment]
@andrewdamelio  :ok_hand:
