### ISSUE TITLE
December Mentor roll call.

### ISSUE THREAD

**Issue by Rchristiani** [nodeschool/toronto#31]
Testing the waters to see if a December event would be ok. 

12th or 19th

Please post below if you can make one of those dates.

**Comment by Rchristiani** [comment]
Available on the 12th, not on the 19th

**Comment by ahmadnassri** [comment]
12 :wave:

**Comment by drewminns** [comment]
12th for me

**Comment by andrewdamelio** [comment]
12th :wave:

**Comment by brenna** [comment]
12th!

**Comment by richgilbank** [comment]
Shopify's Christmas party is on the 12th, but I believe we're not hosting it at the office, so it should be doable

**Comment by ahmadnassri** [comment]
NodeSchoolTO christmas party? ;)

**Comment by wisamjs** [comment]
12th works for me as well. 19th doesn't.

**Comment by vladikoff** [comment]
Cannot do 12th, traveling. Don't let that stop you though ;)

**Comment by jrdnndtsch** [comment]
I could do the 12th :)

**Comment by chrismendis** [comment]
I should be available for December 12th.

**UPDATE**: I'm a strong :+1: for the 12th.

**Comment by darcyclarke** [comment]
:+1: I'm in

**Comment by andrewdamelio** [comment]
👍 12th

**Comment by jeffjewiss** [comment]
:+1: 12th

**Comment by jeffjewiss** [comment]
Looks like we have lots of people available on the 12th.

@richgilbank do you think hosting it at Shopify would work with your schedule or should we try out a new venue for December?

**Comment by richgilbank** [comment]
:ok_hand: I think we're good...the space is booked and requests are in for security, unlocking the elevator and a pause in construction. Will confirm once I hear back, but we have the space anyway :)

**Comment by jeffjewiss** [comment]
Oh wicked, thanks Rich!

I created a checklist for the event: https://github.com/nodeschool/toronto/issues/37
