### ISSUE TITLE
November Discussion Points - Feedback Form

### ISSUE THREAD

**Issue by darcyclarke** [nodeschool/toronto#34]
Here are the talking points from the November meetup as well as some of the information we'd like to add to the feedback form we'll be sending out to attendees.
### Internal Notes
- Send out thanks/feedback form to attendees
- Determine and outline a way to streamline adding new mentors (ie. requiring a vote by committee, attending multiple events, involvement in the community/slack channel, sharing demos, doing a talk etc.)
- Outline the format, schedule and request attendee demos in email communication leading up to an event
- Provide name tags for the next event
- Add Shopify's logo to the site as an ongoing sponsor (they now cover food, drinks, security and the venue for our events)
- Determine if we should run a December event 
- Try out a hands-on workshop to run in parallel of the January event (potential topics: NodeBots, Express, Sails.js, WebPack, Mongoose)
- Try out an elongated schedule (an hour to the end or beginning) with more substantial food options for the January event
### Feedback Form
- Which would you prefer 12:00pm - 4:00pm or 1:00pm - 5:00pm (radio)
- Would you appreciate a more substantial food option at the beginning or end of our events? (Y/n)
- Would you attend a more directed, hands-on workshop if available? (Y/n)
  - What topics would you like to learn about? (text field)(comma separated)
- How can we stay better connected with you and the community? (text field)
- Would you come back? (Y/n)
  - Why or Why not? (text field)
- Would you tell your friends about this event? (Y/n)
  - Why or Why not? (text field)
- Are you looking for a job in Node? (Y/n)
- Why did or are you coming to these events? (multiple choice)
  - Looking for a new job or to switch roles
  - Work on personal projects
  - Hang out and socialize
  - Education 
  - Other (text field)

---

/cc @jeffjewiss @rickycodes @ahmadnassri @brenna @richgilbank @vladikoff @jrdnndtsch @tessalt @fishrock123 @wzaghal @neilff @chrismendis 
I'd like some :+1:'s before I feel comfortable sending out the form to attendees; If you can, please review before tomorrow night and provide feedback if any. Would like to get this out ASAP so that the event is still fresh in people's minds.

**Comment by wisamjs** [comment]
Great work @darcyclarke. The questions on the feedback form look good. How do you plan to send them out? I've used [Typeform](http://www.typeform.com/) before and really liked their UX. 

If I may suggest adding a general question at the top of the form like "What did you think of the last Nodeschool event?". Reason being that that might get them to start thinking of their experience as a whole, so that they might have ideas when they reach questions like "How can we stay better connectef with you and the community"?

I also wonder whether it's worth asking them to rate their experience with Node, or get some clarification on how much Node they work with on their day to day. It might help us gauge our audiences comfort level which might help us come up with more lightening talks or demos.

Lastly, regarding food, should we ask about dietary restrictions? Or should we always make an effort to have food that is at the very least, vegetarian and gluten-free?

Open to criticisms and thoughts. Regardless, the form itself look great.

**Comment by brenna** [comment]
If typeform is easy to set up and can handle what we need on the free account, I say go for it. Have you had experience creating typeform forms, @wzaghal & @darcyclarke ?  

If for some reason that doesn't work out, google forms is straightforward and definitely quick to get set up. I can help with that tomorrow if needed.

@darcyclarke let's be sure to add the question to asses interest in a December event "would you be interested in a December 12th event of would you prefer we take a holiday break?" (or similar)

**Comment by wisamjs** [comment]
I can set up the typeform form by by tomorrow if needed.

**Comment by Rchristiani** [comment]
:ok_hand:

**Comment by chrismendis** [comment]
@darcyclarke thanks so much for putting this together!

One bit of take-it-or-leave-it feedback on the elongated schedule question: does it make sense add an option for those who like the schedule as it is (e.g. "No change (1:00pm - 4:00pm)")?

:+1:

**Comment by chrismendis** [comment]
Also, I'm more than happy to undergo any type of mentor screening process that you put in to place. :smile:

**Comment by rickycodes** [comment]
@darcyclarke LGTM :+1:

@chrismendis, you're cool to mentor if you want. things are pretty free-form. Nobody was really "vetted" in the beginning. However, I believe there should be a process for people who are unknown that want to mentor. (I believe we already had you down to mentor and I know you know your stuff :smile:)

**Comment by brenna** [comment]
regarding mentor vetting, i think anyone who's been to multiple events and gets the NodeSchool environment is okay. It's less about technical skill level (people generally won't offer unless they're capable), but rather more about keeping jerks with bad attitudes out.

**Comment by rickycodes** [comment]
:100:% agree

**Comment by darcyclarke** [comment]
@chrismendis you're :+1:! The thought here was going forward we want to standardize the process. For instance, Drew let me know he wanted to help out and mentor and I was a bit too quick to put him on the site and he subsequently missed the last meet up... not sure what happened there but it's not fair to have someone listed as a mentor if they've never even come to an event or participated. So it's those kinds of situations I want to avoid in the future.

We're stoked to have you on board and I think it'll be fun to see how we can grow the event/community together :)

**Comment by jeffjewiss** [comment]
@darcyclarke thanks for putting this together, looks great and I agree with everyone's suggestions.

@wzaghal will you be setting up and sending out the Typeform today? Do you need an exported list of attendees? Should it be just those who checked in or the full list?

**Comment by darcyclarke** [comment]
@jeffjewiss @wzaghal I'm putting together a Google Form right now... just seemed like the easiest thing

**Comment by jeffjewiss** [comment]
@darcyclarke sounds good! Let me know if I can help with the email list.

**Comment by wisamjs** [comment]
@darcyclarke sounds good. I'll put together the typeform anyway, just to share it later with the team to get everyone's opinion.

**Comment by darcyclarke** [comment]
I sent out the form and will close this issue. I'm going to add the internal notes to the wiki.
