### ISSUE TITLE
Really like the website.. do you automate mentor/attendee lists?

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/toronto#41]

**Comment by darcyclarke** [comment]
Hey @iancrowther! We do indeed. Check out the following script: https://github.com/nodeschool/toronto/blob/gh-pages/tasks/update-attendees.js

You'll need to provide your own `config.json` file that contains a [Tito](https://ti.to) Auth Token for it to work but you could generally utilize it's concepts to get your own version of an attendees listing. For mentors, we simply use a ["mentor" object](https://github.com/nodeschool/toronto/blob/gh-pages/_config.yml#L26) and [loop through that in Jekyll](https://github.com/nodeschool/toronto/blob/gh-pages/_layouts/index.html#L244).

Hope that gives you some insight into how we made the site and appreciate that you like it! :smile:
