### ISSUE TITLE
[brainstorm] telling a story over the events' timeline 

### ISSUE THREAD

**Issue by ahmadnassri** [nodeschool/toronto#52]
we take a picture at the end of every event, what if we can somehow design/plan the pictures to tell a story of the progression over time...

not sure what the concept / idea would be, but this is a good place to discuss.

**Comment by darcyclarke** [comment]
I think simply making a better photo gallery/display would help make an impact immediately. That said, leading up to our 1 year anniversary, I think it would be awesome if we could try to do something at bit bigger, like a putting together a little video. 

@ahmadnassri do you have video equipment we might be able to use? I'm thinking we could interview mentors, and some attendees, about their experience(s) around NodeSchoolTO... then clip it together to make a nice intro video we can share. 

@nodeschool/toronto-mentors thoughts?

**Comment by ahmadnassri** [comment]
I have some lights, mics and go-pros, perfect setup for "interviews"

**Comment by darcyclarke** [comment]
@ahmadnassri did you figure out what the issue was with the go pro? I can ask around to see if I can get someone else's gear just so we have something to shoot with next event if not.

**Comment by ahmadnassri** [comment]
when's next event date?

**Comment by darcyclarke** [comment]
April 16th. Just made a new issue for it and the Mentor Role Call

**Comment by ahmadnassri** [comment]
oh yes, aim to have it fixed waaaay before then, worst case I'm buying a new one. (because I need it)

**Comment by darcyclarke** [comment]
So the video seems to be a no-go. Going to close this issue and we can re-open another at a later date if there's interest again.
