### ISSUE TITLE
February Mentor Roll Call - Feb 27th

### ISSUE THREAD

**Issue by Rchristiani** [nodeschool/toronto#53]
:+1:

**Comment by jrdnndtsch** [comment]
👌

**Comment by vladikoff** [comment]
:+1:

**Comment by brenna** [comment]
🚫@andrewdamelio and I are out of town

**Comment by tessalt** [comment]
:+1: this time for sure I swear!

**Comment by wisamjs** [comment]
I'll be there or be :black_large_square:

**Comment by jeffjewiss** [comment]
:+1:

**Comment by ahmadnassri** [comment]
:+1:

**Comment by darcyclarke** [comment]
:+1:

**Comment by chrismendis** [comment]
[![selfie-0](http://i.imgur.com/6vdc0XF.png)](https://github.com/thieman/github-selfies/)

**Comment by darcyclarke** [comment]
![photo on 2016-02-10 at 2 37 pm](https://cloud.githubusercontent.com/assets/459713/12959297/da340a18-d003-11e5-9520-9dee72ff5326.jpg)

> totes stealing @chrismendis' idea :+1:

**Comment by Fishrock123** [comment]
I'll also be coming! (for once lol)
