### ISSUE TITLE
February Guided Workshop - "Node.js 101"

### ISSUE THREAD

**Issue by darcyclarke** [nodeschool/toronto#54]
@nodeschool/toronto-mentors I'm looking for 2 mentors to help me during the guided workshop that will be run in the larger boardroom of the Shopify office, in-between the talks and demo time (ie. **1:30pm to 3:30pm**). The focus is on _Node.js Basics_ and getting a simple site up and running. Attendees should be required to have some previous front-end + JavaScript experience.

I'll work on a more formal outline and share it with the mentors for review within a week or so. If anyone has suggestions about important material to cover in a _101_ workshop please share in the comments below. 

**Key takeaways for attendees:**
- understanding of what node is good at and useful for
- understanding of how to build and run a basic node server

**Comment by vladikoff** [comment]
@darcyclarke I can help!

**Comment by jeffjewiss** [comment]
I can help as well!
