### ISSUE TITLE
March 19th Mentor Roll Call

### ISSUE THREAD

**Issue by Rchristiani** [nodeschool/toronto#56]
:+1:

**Comment by tessalt** [comment]
:+1:

**Comment by andrewdamelio** [comment]
:+1: and :+1: for @vanessayuenn

**Comment by vladikoff** [comment]
:+1:

**Comment by jrdnndtsch** [comment]
:+1:

**Comment by rickycodes** [comment]
:-1: :cry:

**Comment by pippinlee** [comment]
👍

**Comment by darcyclarke** [comment]
![photo on 2016-03-10 at 2 22 pm](https://cloud.githubusercontent.com/assets/459713/13681504/7afa51e0-e6cb-11e5-87d0-451fcc3a0cc0.jpg)

> the face of a man fuelled on coffee

**Comment by richgilbank** [comment]
![](https://media0.giphy.com/media/3o7abonV6K9irq7kaY/giphy.gif)

At least for a little while - leaving Sunday to give a talk so I may be doing some work through it.

**Comment by jeffjewiss** [comment]
:+1:
