### ISSUE TITLE
April 16th Mentor Role Call

### ISSUE THREAD

**Issue by darcyclarke** [nodeschool/toronto#58]
We'll be running the event out of Lighthouse Labs' DevHub. Hopefully most people can make it (we'll be trying to get some special guests out to visit too).

:+1: 

![photo on 2016-03-24 at 3 01 pm](https://cloud.githubusercontent.com/assets/459713/14028113/4c590bea-f1d1-11e5-8a1b-d8c5222f70e6.jpg)

**Comment by andrewdamelio** [comment]
:+1:

**Comment by Rchristiani** [comment]
:+1:

**Comment by ahmadnassri** [comment]
:+1:

**Comment by chrismendis** [comment]
[![selfie-2](http://i.imgur.com/FF0HWIH.png)](https://github.com/thieman/github-selfies/)

**Comment by ahmadnassri** [comment]
oh fine ... a picture it is ...

![](https://www.dropbox.com/s/d0yc8eo61zoclup/IMG_20160324_150322.jpg?dl=1)

**Comment by brenna** [comment]
:+1:

**Comment by pippinlee** [comment]
👍

**Comment by vanessayuenn** [comment]
:+1:

**Comment by richgilbank** [comment]
![](http://cl.ly/3C3E0A1l1C3x/Image%202016-02-19%20at%2012.28.58%20PM.gif)

**Comment by jrdnndtsch** [comment]
:+1:
