### ISSUE TITLE
May Event Mentor Roll Call

### ISSUE THREAD

**Issue by Rchristiani** [nodeschool/toronto#60]
May 21st. International Node School Day!

**Comment by jrdnndtsch** [comment]
👍  💯

**Comment by vladikoff** [comment]
👍

**Comment by richgilbank** [comment]
![](http://4.bp.blogspot.com/-3CoGVCLhQas/UzX9F9rTg1I/AAAAAAAADvM/BADhQ2AraOw/s1600/tumblr_mjjvjgeLiU1r9uuuso1_500.gif)

**Comment by kr1st1n4gr03g3r** [comment]
Still waiting 5 this 2 happun...

**Comment by chrismendis** [comment]
[![selfie-1](http://i.imgur.com/h2oGqLH.png)](https://github.com/thieman/github-selfies/)

**Comment by vanessayuenn** [comment]
:+1:

**Comment by Fishrock123** [comment]
I'll be coming down. :+1:

**Comment by darcyclarke** [comment]
![photo on 2016-05-20 at 4 09 pm](https://cloud.githubusercontent.com/assets/459713/15440781/58f86d9a-1ea5-11e6-9343-29235c9c4c43.jpg)

👍

**Comment by ahmadnassri** [comment]
humanz showing off opposable thumbs ... I can haz thumbs too?

![image](https://cloud.githubusercontent.com/assets/183195/15443007/e687deea-1eb2-11e6-95c0-75b3207cdc77.png)
