### ISSUE TITLE
June 18th Mentor Roll Call

### ISSUE THREAD

**Issue by Rchristiani** [nodeschool/toronto#64]
👍

**Comment by ahmadnassri** [comment]
:-1: will be in Seattle for Docker Conf :cry:

**Comment by richgilbank** [comment]
![](http://theawesomer.com/photos/2013/03/thumbs_and_ammo_3.jpg)

**Comment by darcyclarke** [comment]
![photo on 2016-06-02 at 3 26 pm](https://cloud.githubusercontent.com/assets/459713/15757996/624612cc-28d6-11e6-902c-ad352309a81b.jpg)

**Comment by tessalt** [comment]
im going to be out of town 👎

**Comment by jrdnndtsch** [comment]
👍

**Comment by rickycodes** [comment]
:raised_hand:

**Comment by jeffjewiss** [comment]
I'll be out of town :-1:

**Comment by tessalt** [comment]
plans changed, I'm in 👍

**Comment by vanessayuenn** [comment]
also out of town :'(
