### ISSUE TITLE
October 29th Roll call 

### ISSUE THREAD

**Issue by Rchristiani** [nodeschool/toronto#66]
👍

**Comment by vladikoff** [comment]
probably 👍

**Comment by vanessayuenn** [comment]
:( gonna be at ng-europe 👎

**Comment by darcyclarke** [comment]
👍

**Comment by kr1st1n4gr03g3r** [comment]
Just a note that I only find out about Node School because I'm subscribed to this repo. I haven't received the emails for the last couple.

I'm too junior to help out, but that's all I got. 🔢

**Comment by darcyclarke** [comment]
@gringogidget heard, noted and appreciated 😄 I know this has been an issue for awhile now. We'll try and be better at informing the community of events ahead of time through our various channels (including the mailing list or emailing previous attendees via tito). @jeffjewiss kept on top of that for awhile but we've unfortunately lost him to the U.K. 😦 so we'll try to pick up the slack.

That said, we'll probably always rely heavily on word-of-mouth to get people notified so if you can spread the word whenever possible, and when you're in the know, that is a huge help.

**Comment by andrewdamelio** [comment]
👍 probably

**Comment by kr1st1n4gr03g3r** [comment]
I could help if needed. - email dev

**Comment by jeffjewiss** [comment]
I can grant more people access to the Mailchimp account, if that helps. There are about 350 subscribers, so I think the emails help in getting people to come out. I've just been copying the same email template every time, so it's not much work.

**Comment by andrewdamelio** [comment]
sure @jeffjewiss, feel free to add me (dev@andrewdamel.io)

**Comment by Rchristiani** [comment]
@gringogidget I have been sending out an email for the events for the last little while, are you just not receiving them? what is the email so I can check the mailing list on mailchimp!

**Comment by pippinlee** [comment]
👍

**Comment by Rchristiani** [comment]
@gringogidget I have sent an email from the mailing list let me know if don't see an email. I have checked you name is on the list.

**Comment by chrismendis** [comment]
I got the `go` signal for this one!

![selfie-0](http://i.imgur.com/2PzzS3s.png)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
