### ISSUE TITLE
April 22nd Mentor Roll Call

### ISSUE THREAD

**Issue by Rchristiani** [nodeschool/toronto#73]
A little late to the party, but who is coming out to mentor this month!

**Comment by vladikoff** [comment]
Maybe!

**Comment by tessalt** [comment]
im in!

**Comment by mikemimik** [comment]
I might be moving, so I'm not sure I can be there this weekend. I guess that makes me a maybe.

**Comment by darcyclarke** [comment]
In

**Comment by ahmadnassri** [comment]
maybe.

**Comment by justincorrigible** [comment]
Can I be of assistance?

**Comment by vanessayuenn** [comment]
🙋🏻🙋🏻 might have to arrive a tad bit later tho
