### ISSUE TITLE
June 17 Mentor Roll Call

### ISSUE THREAD

**Issue by mikemimik** [nodeschool/toronto#76]
Who's going to be around?

**Comment by vladikoff** [comment]
Maybe!

**Comment by tessalt** [comment]
👍

**Comment by darcyclarke** [comment]
I'm a 👎 😞. I'll be up at a cottage, disconnecting from my laptop (unfortunately).

**Comment by pippinlee** [comment]
👍

**Comment by ahmadnassri** [comment]
👍

**Comment by rickycodes** [comment]
👍  i can show a thing too https://github.com/rickycodes/android-drag-and-drop
