### ISSUE TITLE
July 22 Mentor Roll Call

### ISSUE THREAD

**Issue by mikemimik** [nodeschool/toronto#78]
Who's all going to be around?

**Comment by darcyclarke** [comment]
👍 
![photo on 2017-06-21 at 12 22 pm](https://user-images.githubusercontent.com/459713/27395032-57e24e16-567c-11e7-8de2-a0c9aaabbaa6.jpg)

**Comment by Rchristiani** [comment]
👍

**Comment by rickycodes** [comment]
👍

**Comment by vladikoff** [comment]
Probably!
