### ISSUE TITLE
Mentor Roll Call September 23rd 2017

### ISSUE THREAD

**Issue by Rchristiani** [nodeschool/toronto#81]

**Comment by JasonEtco** [comment]
Count me in 👍 🎉 🍕 🌮 🍺 💻

**Comment by mikemimik** [comment]
I will be available for most of it, but will have to leave early.

**Comment by rickycodes** [comment]
👎 I will be in Berlin for https://zeit.co/day :(

**Comment by darcyclarke** [comment]
:+1:

**Comment by Rchristiani** [comment]
Due to unforeseen circumstances, going to be cancelling nodeschool this month.
