### ISSUE TITLE
Mentor Roll Call December 3rd

### ISSUE THREAD

**Issue by JasonEtco** [nodeschool/toronto#84]
# 🔈 🔈 🔈 ROLL CALL 🔈 🔈 🔈

`#whos-in`

[December 3rd Event](https://ti.to/nodeschool-toronto/nodeschool-toronto-december-2017/)

**Comment by darcyclarke** [comment]
👍

**Comment by Rchristiani** [comment]
👌 thanks for setting that up!

**Comment by mikemimik** [comment]
I’m available

**Comment by ahmadnassri** [comment]
:hand:
