### ISSUE TITLE
Mentor Roll Call January 27th

### ISSUE THREAD

**Issue by mikemimik** [nodeschool/toronto#85]
Who's gonna be around?

![kevin-hart-me](https://user-images.githubusercontent.com/2818462/34860176-bf824db6-f729-11e7-99f4-f08db27f5bad.gif)

**Comment by JasonEtco** [comment]
~I may have to skip, or I may come and catch up on work on my laptop like a nerd; TBD~ 🌮 

I'll be there 👍

**Comment by ahmadnassri** [comment]
🙋🏼‍♂️

**Comment by tessalt** [comment]
probably not, I'll probably be moving. But maybe!

**Comment by pippinlee** [comment]
Yup

**Comment by erichwelz** [comment]
I can mentor. First timer, have gone through the exercises. What time should I be there?

**Comment by mikemimik** [comment]
@erichwelz Just come when you have time, it's not required to come early just because you're a mentor. I'm not sure what we'll have to setup at this venue so if you'd like to figure that out with us, you could be there a little early. Ping someone on slack when you arrive, if you can't find anyone.

**Comment by erichwelz** [comment]
Eh, turns out I can't. Thank @mikemimik
