### ISSUE TITLE
Mentor Roll Call February 24th, 2018

### ISSUE THREAD

**Issue by mikemimik** [nodeschool/toronto#88]
Y'all gonna show up?

**Comment by JasonEtco** [comment]
![gif](https://media.giphy.com/media/TNOq5o37nNXX2/giphy.gif)

**Comment by vladikoff** [comment]
<details><summary> 🐙  </summary><p>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> I <hr> will <hr></hr>  be </hr> there <hr/>

</p></details>

**Comment by Rchristiani** [comment]
![](https://media.giphy.com/media/oGP0Sv692lb68/giphy.gif)
