### ISSUE TITLE
Mentor Roll Call August 25th, 2018

### ISSUE THREAD

**Issue by mikemimik** [nodeschool/toronto#91]
Who's going to be around?

![](https://user-images.githubusercontent.com/2818462/34860176-bf824db6-f729-11e7-99f4-f08db27f5bad.gif)

**Comment by richgilbank** [comment]
![](https://media3.giphy.com/media/26tk0un0aZrXwDrVu/giphy.gif)

**Comment by JasonEtco** [comment]
![](https://78.media.tumblr.com/tumblr_lp24t0dj0C1r0t1dvo1_500.gif)

I'll be in SF 😭
